### ISSUE TITLE
Error: Cannot run program "G:\graalvm-ce-java11-20.0.0\bin\java.exe": CreateProcess error=206

### ISSUE THREAD

**Issue by iwangxiaodong** [newk5/quarkus-jsf#1]
@newk5 

Windows 10 x64 + graalvm 20.0.0 + java11

build.gradle added：

    implementation group: 'org.apache.myfaces.core.extensions.quarkus', name: 'myfaces-quarkus-deployment', version: '2.3-next-M2'
    implementation group: 'org.apache.myfaces.core.extensions.quarkus', name: 'myfaces-quarkus-runtime', version: '2.3-next-M2'

**gradle buildNative**

Error: Cannot run program "G:\graalvm-ce-java11-20.0.0\bin\java.exe": CreateProcess error=206

Thanks!

**Comment by newk5** [comment]
Sorry, no idea how to get this running with gradle, all my tests were on maven.

**Comment by iwangxiaodong** [comment]
@newk5 

I wrote gradle example：

download [quarkus-example.zip](https://github.com/iwangxiaodong/temporary-thing/raw/master/anything/quarkus-example.zip)

https://gradle.org/install/

gradle clean

gradle --configure-on-demand -x check buildNative

Visit url http://localhost:8080/demo

build.gradle added：myfaces-quarkus library.

If you have time to help me, Please!

**Comment by iwangxiaodong** [comment]
Found official myfaces-quarkus - [https://github.com/apache/myfaces/tree/master/extensions/quarkus/showcase](https://github.com/apache/myfaces/tree/master/extensions/quarkus/showcase)
